version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:19
    steps:
      - checkout
      - run:
          name: "Build and Test"
          command: "./gradlew build"

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
